# Generated by Django 4.0.5 on 2022-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='product',
            field=models.ManyToManyField(to='clientes.product'),
        ),
    ]
