# Generated by Django 4.0.5 on 2022-07-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_product_price_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
